# Generated by Django 4.2.10 on 2024-02-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
