# Generated by Django 4.2.10 on 2024-02-09 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auctions_bought', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='auction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='auction.auction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transation',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transations_getter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('UA', 'Ukraine'), ('POL', 'Poland'), ('USA', 'United States of America'), ('CAN', 'Canada'), ('UK', 'United Kingdom'), ('FRA', 'France'), ('GER', 'Germany'), ('AUS', 'Australia')], default='UA', max_length=4),
        ),
        migrations.AlterField(
            model_name='transation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transations_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
