# Generated by Django 4.2.10 on 2024-02-10 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_better',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auctions_betters', to=settings.AUTH_USER_MODEL),
        ),
    ]
