# Generated by Django 4.2.10 on 2024-02-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_buyer_lot_auction_transation_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='name',
            field=models.CharField(default='Auction', max_length=255),
        ),
    ]
