# Generated by Django 4.2.10 on 2024-02-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_auction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='seconds_to_end',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
