# Generated by Django 4.2.10 on 2024-02-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_auction_seconds_to_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='seconds_to_end',
            field=models.IntegerField(default=60),
        ),
    ]
