# Generated by Django 4.2.10 on 2024-02-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_auction_seconds_to_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
