# Generated by Django 4.2.10 on 2024-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_alter_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/avatars/default_user.png', upload_to='media/avatars'),
        ),
    ]
