# Generated by Django 4.2.10 on 2024-02-11 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_auction_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='participants',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
