# Generated by Django 4.2.10 on 2024-02-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_alter_auction_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Auction', max_length=255)),
                ('description', models.TextField(blank=True, max_length=700, null=True)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minimal_bet', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_of_ransom', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_start', models.DateTimeField()),
            ],
        ),
    ]
