# Generated by Django 5.0.2 on 2024-02-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_auction2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction2',
            name='time_of_start',
            field=models.DateTimeField(null=True),
        ),
    ]
